Revert "snap: Further snap build testing"
This reverts commit a9a47d44f65507bd5a8d5669c8ab79d517cd0863.

The commit was only for testing why snap builds were using the wrong
kernel header files.

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -67,10 +67,6 @@ parts:
       snapcraftctl set-version $VER
       echo -n "Build kernel:"
       printf " %d.%d.%d\n" $(printf "%6.6x" $(grep LINUX_VERSION_CODE /usr/include/linux/version.h | sed -e "s/.*CODE //") | sed -e "s/\(..\)\(..\)/0x\1 0x\2 0x/")
-      ARCH=$(dpkg-architecture -q DEB_BUILD_ARCH)
-      if [ $ARCH != amd64 ]; then
-          exit 1  # Save wasting snap builders' time
-      fi
     build-packages:
       - iptables-dev
       - libipset-dev
@@ -120,7 +116,7 @@ parts:
       dpkg -x ${SNAPCRAFT_PART_INSTALL}/linux-libc-dev.deb ${SNAPCRAFT_PART_INSTALL}
       printf " %d.%d.%d\n" $(printf "%6.6x" $(grep LINUX_VERSION_CODE ${SNAPCRAFT_PART_INSTALL}/usr/include/linux/version.h | sed -e "s/.*CODE //") | sed -e "s/\(..\)\(..\)/0x\1 0x\2 0x/")
       rm -f ${SNAPCRAFT_PART_INSTALL}/linux-libc-dev.deb
-      echo Running as $(id)
+      echo Running as $id
       echo Pull SNAPCRAFT_PART_INSTALL=${SNAPCRAFT_PART_INSTALL}
       echo Pull dirs = $(find ${SNAPCRAFT_PART_INSTALL} -type d)
       ARCH_DIR=$(ls -d ${SNAMCRAFT_PART_INSTALL}/usr/include/*/asm)
@@ -128,26 +124,18 @@ parts:
       echo $ARCH_DIR $ARCH_DIR1
     override-build: |
       snapcraftctl build
-      echo Build Running as $(id)
+      echo Build Running as $id
       echo Build SNAPCRAFT_PART_INSTALL=${SNAPCRAFT_PART_INSTALL}
       echo Build dirs = $(find ${SNAPCRAFT_PART_INSTALL} -type d)
-      echo /usr/include/linux -
       ls -ld /usr/include/linux
-      ARCH_DIR=$(ls -d ${SNAMCRAFT_PART_INSTALL}/usr/include/*/asm | sed -e "s:/asm$::" -e "s:.*/::")
+      exit 1  # Force build failure
       # Move the headers on the host out of the way
-      HEADER_DIRS={linux,asm-generic,${ARCH_DIR}/asm}
+      HEADER_DIRS={linux,asm-generic}
       rm -rf /usr/include/${HEADER_DIRS} || true
-      echo /usr/include dirs now -
-      ls -l /usr/include | grep "^d"
       # Move header from the part to the host
-      echo mv ${SNAPCRAFT_PART_INSTALL}/usr/include now -
-      ls -l ${SNAPCRAFT_PART_INSTALL}/usr/include
       mv ${SNAPCRAFT_PART_INSTALL}/usr/include/${HEADER_DIRS} /usr/include/ || true
-      echo /usr/include dirs after mv now -
-      ls -l /usr/include | grep "^d"
       echo -n "Build kernel:"
       printf " %d.%d.%d\n" $(printf "%6.6x" $(grep LINUX_VERSION_CODE /usr/include/linux/version.h | sed -e "s/.*CODE //") | sed -e "s/\(..\)\(..\)/0x\1 0x\2 0x/")
-      exit 1  # Force build failure
     stage:
       - -*
     prime:
